// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadForwarder returns the embedded CollectionSpec for forwarder.
func loadForwarder() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ForwarderBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load forwarder: %w", err)
	}

	return spec, err
}

// loadForwarderObjects loads forwarder and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*forwarderObjects
//	*forwarderPrograms
//	*forwarderMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadForwarderObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadForwarder()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// forwarderSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type forwarderSpecs struct {
	forwarderProgramSpecs
	forwarderMapSpecs
	forwarderVariableSpecs
}

// forwarderProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type forwarderProgramSpecs struct {
	XdpForwarder *ebpf.ProgramSpec `ebpf:"xdp_forwarder"`
}

// forwarderMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type forwarderMapSpecs struct {
}

// forwarderVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type forwarderVariableSpecs struct {
}

// forwarderObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadForwarderObjects or ebpf.CollectionSpec.LoadAndAssign.
type forwarderObjects struct {
	forwarderPrograms
	forwarderMaps
	forwarderVariables
}

func (o *forwarderObjects) Close() error {
	return _ForwarderClose(
		&o.forwarderPrograms,
		&o.forwarderMaps,
	)
}

// forwarderMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadForwarderObjects or ebpf.CollectionSpec.LoadAndAssign.
type forwarderMaps struct {
}

func (m *forwarderMaps) Close() error {
	return _ForwarderClose()
}

// forwarderVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadForwarderObjects or ebpf.CollectionSpec.LoadAndAssign.
type forwarderVariables struct {
}

// forwarderPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadForwarderObjects or ebpf.CollectionSpec.LoadAndAssign.
type forwarderPrograms struct {
	XdpForwarder *ebpf.Program `ebpf:"xdp_forwarder"`
}

func (p *forwarderPrograms) Close() error {
	return _ForwarderClose(
		p.XdpForwarder,
	)
}

func _ForwarderClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed forwarder_bpfel.o
var _ForwarderBytes []byte
